---
title: "Testing"
author: "Sophia Leiker"
date: "4/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
library(broom)
library(equatiomatic)
```

```{r}
water <- read_csv(here("data", "Water_Districts.csv")) %>% 
  clean_names() %>% 
  mutate(mc_aggregate = mc_kern + mc_antelope + mc_ventura + mc_mojave)
water_longer <- water %>% 
  pivot_longer(cols = c(3:6), names_to = "county", values_to = "mc") %>% 
  mutate(county = case_when(
    county == "mc_kern" ~ "Kern", 
    county == "mc_antelope" ~ "Antelope", 
    county == "mc_ventura" ~ "Ventura", 
    county == "mc_mojave" ~ "Mojave",
    county == "mc_aggregate" ~ "Aggregate"
  ))
```

```{r}
ggplot(data = water_longer, 
       aes(x = reduction, y = mc, color = county)) +
  geom_line(size = 0.3) + 
  geom_smooth(method = "lm") +
  theme_minimal(14) +
  labs (y = "Marginal cost of abatement ($/acre foot)", 
        x = "Level of reduction (acre feet)") +
  scale_color_manual(values = c("cyan4", "goldenrod4", "firebrick", "forestgreen")) +
  theme(legend.position = c(0.2, 0.7))
```


```{r}
lm_kern <- lm(mc_kern ~ 0 + reduction, data = water)
lm_ventura <- lm(mc_ventura ~ 0 + reduction, data = water)
lm_antelope <- lm(mc_antelope ~ 0 + reduction, data = water)
lm_mojave <- lm(mc_mojave ~ 0 + reduction, data = water)
lm_aggregate <- lm(mc_aggregate ~ 0 + reduction, data = water)
```

```{r}
extract_eq(lm_kern, use_coefs = TRUE)
extract_eq(lm_ventura, use_coefs = TRUE)
extract_eq(lm_antelope, use_coefs = TRUE)
extract_eq(lm_mojave, use_coefs = TRUE)
extract_eq(lm_aggregate, use_coefs = TRUE)
```

```{r}
slope_kern <- lm_kern$coefficients[1]
slope_ventura <- lm_ventura$coefficients[1]
slope_antelope <- lm_antelope$coefficients[1]
slope_mojave <- lm_mojave$coefficients[1]
slope_aggregate <- lm_aggregate$coefficients[1]
```

