---
title: "Water Markets"
author: "Sophia Leiker"
date: "4/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
library(equatiomatic)
```


```{r}
#reading in the data
water <- read_csv(here("data", "Water_Districts.csv"))
```

## Kern

Fitting a line
```{r}
model.kern <- lm(MC_Kern ~ 0 + Reduction, data = water)
model.mojave <- lm(MC_Mojave ~ 0 + Reduction, data = water)
model.antelope <- lm(MC_Antelope ~ 0 + Reduction, data = water)
model.ventura <- lm(MC_Ventura ~ 0 + Reduction, data = water)
```

Getting the Slope
```{r}
B_kern <- model.kern$coefficient[1]
B_mojave <- model.mojave$coefficient[1]
B_antelope <- model.antelope$coefficient[1]
B_ventura <- model.ventura$coefficient[1]
```


```{r}
water <- water %>% 
  mutate(mc_aggregate = MC_Kern + MC_Antelope + MC_Ventura + MC_Mojave)

water_longer <- water %>% 
  pivot_longer(cols = c(3:6), names_to = "county", values_to = "mc") %>% 
  mutate(county = case_when(
    county == "MC_Kern" ~ "Kern", 
    county == "MC_Antelope" ~ "Antelope", 
    county == "MC_Ventura" ~ "Ventura", 
    county == "MC_Mojave" ~ "Mojave",
    county == "MC_Aggregate" ~ "Aggregate"
  ))
```

```{r}
ggplot(data = water_longer, 
       aes(x = Reduction, y = mc, color = county)) +
  geom_point(size = 0.2) + 
  geom_smooth(method = "lm") +
  theme_minimal(14) +
  labs (y = "Marginal cost to Abate ($/acre foot)", 
        x = "Reduction (acre feet)",
        title = "Marginal Abatement Cost") +
  scale_color_manual(values = c("yellow", "blue", "red", "forestgreen")) +
  scale_y_continuous(limits = c(0, 500)) +
  scale_x_continuous(limits = c(0, 150)) +
  theme_minimal()
```

```{r}
lm_aggregate <- lm(mc_aggregate ~ 0 + Reduction, data = water_longer)
slope_aggregate <- lm_aggregate$coefficients[1]
```

##### SWITCHING CODE ########
Predicting by multiplying a vector of abatement number by the slope selected above
```{r}
predicted.mc_kern <- B_kern*seq(0,140,1)

#Adding new column to the water data frame
water_demand <- water %>% 
  #mutate(demand = steps) %>% 
  mutate(Predicted_MC_Kern = predicted.mc_kern)

ggplot(data = water_demand, aes(x=Reduction, y = Predicted_MC_Kern))+
  geom_line(color = "forestgreen") +
  labs(title = "Marginal Cost Kern Line") +
    geom_point(aes(x=Reduction, y = MC_Kern))

extract_eq(model.kern, use_coefs = TRUE)
slope_kern <- model.kern$coefficients[1]
```


***

## MOJAVE

```{r}
predicted.mc_mojave <- B_mojave*seq(0,140,1)

#Adding new column to the water data frame
water_demand <- water_demand %>% 
  mutate(Predicted_MC_Mojave = predicted.mc_mojave)

ggplot(data = water_demand, aes(x=Reduction, y = Predicted_MC_Mojave))+
  geom_line(color = "Red") +
  labs(title = "Marginal Cost Mojave Line") +
    geom_point(aes(x=Reduction, y = MC_Mojave))

extract_eq(model.mojave, use_coefs = TRUE)
slope_mojave <- model.mojave$coefficients[1]
```


***

## Antelope


```{r}
predicted.mc_antelope <- B_antelope*seq(0,140,1)

#Adding new column to the water data frame
water_demand <- water_demand %>% 
  mutate(Predicted_MC_Antelope = predicted.mc_antelope)

ggplot(data = water_demand, aes(x=Reduction, y = Predicted_MC_Antelope))+
  geom_line(color = "Blue") +
  labs(title = "Marginal Cost Antelope Line") +
    geom_point(aes(x=Reduction, y = MC_Antelope))

extract_eq(model.antelope, use_coefs = TRUE)
slope_antelope <- model.antelope$coefficients[1]
```

***

## Ventura


```{r}
predicted.mc_ventura <- B_ventura*seq(0,140,1)

#Adding new column to the water data frame
water_demand <- water_demand %>% 
  mutate(Predicted_MC_Ventura = predicted.mc_ventura)

ggplot(data = water_demand, aes(x=Reduction, y = Predicted_MC_Ventura))+
  geom_line(color = "Purple") +
  labs(title = "Marginal Cost Ventura Line") +
    geom_point(aes(x=Reduction, y = MC_Ventura))

extract_eq(model.ventura, use_coefs = TRUE)
slope_ventura <- model.ventura$coefficients[1]
```

***

## 2 Demand Curve


```{r}

demand_kern <- B_kern*c(150:0)
demand_mojave <- B_mojave*c(140:0)
demand_antelope <- B_antelope*c(220:0)
demand_ventura <- B_ventura*c(245:0)

#Adding new column to the water data frame
water_demand <- water_demand %>% 
  mutate(demand_kern = demand_kern) %>% 
  mutate(demand_mojave = demand_mojave) %>% 
  mutate(demand_antelope = demand_antelope) %>% 
  mutate(demand_ventura = demand_ventura)
  

ggplot(data = water_demand, aes(x=Reduction, y = demand_kern))+
  geom_line(color = "green") +
  labs(title = "Demand Lines", y = "Demand ($/acre foot)") +
  geom_line(color = "red", aes(x=Reduction, y = demand_mojave)) +
  geom_line(color = "blue", aes(x=Reduction, y = demand_antelope)) +
  geom_line(color = "purple", aes(x=Reduction, y = demand_ventura))
```

```{r}
#NEW CODE HERE
water2 <- water %>% clean_names() %>% 
  mutate(mc_aggregate = mc_kern + mc_antelope + mc_ventura + mc_mojave)

reduction_inverse <- c(140:0)
water_inverse <- data.frame(reduction_inverse, water2) 
water_inverse_longer <- water_inverse %>% 
  pivot_longer(cols = c(4:7), names_to = "county", values_to = "mc") %>% 
  mutate(county = case_when(
    county == "mc_kern" ~ "Kern", 
    county == "mc_antelope" ~ "Antelope", 
    county == "mc_ventura" ~ "Ventura", 
    county == "mc_mojave" ~ "Mojave"
  ))
ggplot(data = water_inverse_longer, 
       aes(x = reduction_inverse, y = mc, color = county)) +
  geom_line(size = 0.3) + 
  geom_smooth(method = "lm") +
  theme_minimal(14) +
  labs (y = "Marginal benefit of water use ($/acre foot)", 
        x = "Water use (consumption) (acre feet)")
```

